spring:
  application:
    name: ecommerce-api
  datasource:
    url: jdbc:h2:mem:ecommerce
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

server:
  port: 8080

logging:
  level:
    com.example.demo: DEBUG

api:
  security:
    token:
      secret: ${JWT_SECRET:my-super-secret-jwt-key-that-is-at-least-256-bits-long-123456}