INSERT INTO CATEGORIA (ID_CATEGORIA, NOME, DESCRICAO, STATUS, CREATED_AT, UPDATED_AT) VALUES (1, 'Blusa', 'Blusas diversas', 'ATIVO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CATEGORIA (ID_CATEGORIA, NOME, DESCRICAO, STATUS, CREATED_AT, UPDATED_AT) VALUES (2, 'Calça', 'Calças jeans e tecido', 'ATIVO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CATEGORIA (ID_CATEGORIA, NOME, DESCRICAO, STATUS, CREATED_AT, UPDATED_AT) VALUES (3, 'Vestido', 'Vestidos longos e curtos', 'ATIVO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CATEGORIA (ID_CATEGORIA, NOME, DESCRICAO, STATUS, CREATED_AT, UPDATED_AT) VALUES (4, 'Saia', 'Saias diversas', 'ATIVO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CATEGORIA (ID_CATEGORIA, NOME, DESCRICAO, STATUS, CREATED_AT, UPDATED_AT) VALUES (5, 'Short', 'Shorts', 'ATIVO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CATEGORIA (ID_CATEGORIA, NOME, DESCRICAO, STATUS, CREATED_AT, UPDATED_AT) VALUES (6, 'Moda Praia', 'Biquínis e maiôs', 'ATIVO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CATEGORIA (ID_CATEGORIA, NOME, DESCRICAO, STATUS, CREATED_AT, UPDATED_AT) VALUES (7, 'Beleza', 'Cosméticos e cuidados', 'ATIVO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CATEGORIA (ID_CATEGORIA, NOME, DESCRICAO, STATUS, CREATED_AT, UPDATED_AT) VALUES (8, 'Jaqueta', 'Jaquetas e casacos', 'ATIVO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO CATEGORIA (ID_CATEGORIA, NOME, DESCRICAO, STATUS, CREATED_AT, UPDATED_AT) VALUES (9, 'Infantil', 'Moda para crianças', 'ATIVO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);